[tool.poetry]
name = "banking-widget"
version = "0.1.0"
description = ""
authors = ["Simon"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
python-dotenv = "^1.1.0"
requests = "^2.32.3"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.1.1"
black = "^24.10.0"
isort = "^5.13.2"
mypy = "^1.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
[tool.black]
line-length = 119  # Максимальная длина строки
exclude = '\.git'  # Исключение папки .git

[tool.isort]
line_length = 119  # Максимальная длина строки
# Параметры для isort, чтобы форматировать не более 1 импорта.
# Обратите внимание, что используется isort >= 5.0.0
profile = "black"
combine_as_imports = false
multi_line_output = 3
include_trailing_comma = true

[tool.mypy]
disallow_untyped_defs = true  # Запрет неаннотированных функций
warn_return_any = true  # Предупреждение о возврате с типом Any
exclude = "venv"  # Исключение папки venv



